// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-upcoming-events.ts
import { createClient } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var list_upcoming_events_default = defineTool({
  name: "list_upcoming_events",
  title: "List upcoming events",
  description: "List upcoming hyperlocal events in the Hop-Inn network (name, location, date). Public read.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum number of events to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: ctx.isAuthenticated() ? { headers: { Authorization: `Bearer ${ctx.getToken()}` } } : void 0,
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("events").select(
      "id, name, description, location_name, event_date, image_url, location_latitude, location_longitude"
    ).gte("event_date", (/* @__PURE__ */ new Date()).toISOString()).order("event_date", { ascending: true }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-rides.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_my_rides_default = defineTool2({
  name: "list_my_rides",
  title: "List my rides",
  description: "List the signed-in Hop-Inn user's rides (most recent first) with pickup, dropoff, status, and fare.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(10),
    status: z2.enum(["pending", "matched", "in_progress", "completed", "cancelled"]).nullable().describe("Optional status filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let query = supabase.from("rides").select(
      "id, pickup_location, dropoff_location, ride_type, status, fare, distance_km, created_at"
    ).order("created_at", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rides: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.84.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_profile_default = defineTool3({
  name: "get_profile",
  title: "Get my profile",
  description: "Return the signed-in Hop-Inn user's profile (name, phone, avatar).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("profiles").select("id, full_name, phone_number, avatar_url").eq("id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            data ?? { id: ctx.getUserId(), email: ctx.getUserEmail() },
            null,
            2
          )
        }
      ],
      structuredContent: {
        profile: data ?? { id: ctx.getUserId(), email: ctx.getUserEmail() }
      }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pxkancixaefgzupjdoin";
var mcp_default = defineMcp({
  name: "hop-inn-mcp",
  title: "Hop-Inn",
  version: "0.1.0",
  instructions: "Tools for the Hop-Inn shared auto-rickshaw app. Use `list_upcoming_events` to browse hyperlocal events, `list_my_rides` to view the signed-in user's ride history, and `get_profile` to fetch their profile.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_upcoming_events_default, list_my_rides_default, get_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
